### PR TITLE
New theme and page structure

### PR DESCRIPTION
**Pull request by arjunrbery**
Need to complete
- [x] Validate theme
- [x] Update style for projects
- [x] Utilize Nivenly font

### CODE REVIEW

**Comment by arjunrbery** [comment]
Hey!

Quick update on what I think is left/some questions

Need:
1. Privacy Policy
2. Logos (Already chatted about that) (I added proper placeholder images)
3. Photos for about us page
4. Blog posts

Questions:
1. Should I utilize the same code of conduct? https://aurae.io/community/code-of-conduct/
2. Which theme do you prefer? 
A. image
B. image
3. Should we use an alternative secondary color? I picked the orange based on the guidebook, but it might be a bit aggressive against the brighter blue
4. Opinions on the favicons?

Open items
1. Need to fix mobile menu nav

**Comment by quintessence** [comment]
> Hey!
> 
> Quick update on what I think is left/some questions
> 
> Need:
> 
> 1. Privacy Policy
> 2. Logos (Already chatted about that) (I added proper placeholder images)
> 3. Photos for about us page
> 4. Blog posts
> 
> Questions:
> 
> 1. Should I utilize the same code of conduct? https://aurae.io/community/code-of-conduct/
> 2. Which theme do you prefer?
>    A. image
>    B. image
> 3. Should we use an alternative secondary color? I picked the orange based on the guidebook, but it might be a bit aggressive against the brighter blue
> 4. Opinions on the favicons?

For the questions:

1. Yes for the same Code of Conduct 

2. (and 3) Yes, the darker blue and the orange from the guidebook. I think the higher contrast helps with keeping the text visible. I do think the SVG logo on the banner should be the no-text logo though.

4. The favicon that is currently in use is great (the no-text logo). :)

For the needs:

for 1 & 4 as long as there's a placeholder to get started (lorem ipsum) we can take it from there

For 2 - do you have the updated logos from GitHub?

For 3 - I'll ask for the headshots and get those to you

**Comment by arjunrbery** [comment]
> 

Sorry for the confusion on number 2. I did get the the Nivenly logos from GitHub, but needed the logos for Aurae and Hachyderm. You said those were in design, but just wanted to log here so that we didn't merge without them.

I'll get started on the rest in a bit

**Comment by quintessence** [comment]
Ah got it! Yes we'll get those to you <3

**Comment by quintessence** [comment]
This is lovely, thank you so much!!

**Pull request merged**
